import type { Metadata } from "next";
import localFont from 'next/font/local';
import { Poppins } from 'next/font/google';
import { Navbar } from "@/components/Navbar";

import "./globals.css";

const storymaker = localFont ({
  src : './StoryMakerGTDemo.ttf',
  variable : '--font-storymaker',
  display : 'swap',
  weight : '400',
})

const poppins = Poppins({
  subsets: ['latin'],
  variable: '--font-poppins',
  weight: '400',
})

export const metadata: Metadata = {
  title: "Wujudkan Inlusivitas",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <main className={`${poppins.variable} ${storymaker.variable}`}>
          <Navbar />
          <div>
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}
